// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUpdateRepository(arg1, arg2) {
  return window['go']['main']['App']['AddUpdateRepository'](arg1, arg2);
}

export function CheckRepoErrors(arg1) {
  return window['go']['main']['App']['CheckRepoErrors'](arg1);
}

export function ChooseRepository() {
  return window['go']['main']['App']['ChooseRepository']();
}

export function CmdCheck() {
  return window['go']['main']['App']['CmdCheck']();
}

export function DeleteRepositoryFromDisk(arg1) {
  return window['go']['main']['App']['DeleteRepositoryFromDisk'](arg1);
}

export function DeleteRepositorySetting(arg1) {
  return window['go']['main']['App']['DeleteRepositorySetting'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['main']['App']['GetRepoInfo'](arg1);
}

export function GetRepoStats(arg1) {
  return window['go']['main']['App']['GetRepoStats'](arg1);
}

export function GetSnapshots(arg1) {
  return window['go']['main']['App']['GetSnapshots'](arg1);
}

export function ListFilesInSnapshots(arg1, arg2) {
  return window['go']['main']['App']['ListFilesInSnapshots'](arg1, arg2);
}

export function ReadWriteSettings() {
  return window['go']['main']['App']['ReadWriteSettings']();
}

export function RestoreRepo(arg1, arg2) {
  return window['go']['main']['App']['RestoreRepo'](arg1, arg2);
}

export function SearchInRepo(arg1, arg2) {
  return window['go']['main']['App']['SearchInRepo'](arg1, arg2);
}
