// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseRepository():Promise<string>;

export function CmdCheck():Promise<string>;

export function GetSnapshots(arg1:string):Promise<string>;

export function ReadWriteSettings():Promise<void>;
