// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUpdateRepository(arg1, arg2) {
  return window['go']['main']['App']['AddUpdateRepository'](arg1, arg2);
}

export function ChooseRepository() {
  return window['go']['main']['App']['ChooseRepository']();
}

export function CmdCheck() {
  return window['go']['main']['App']['CmdCheck']();
}

export function GetSnapshots(arg1) {
  return window['go']['main']['App']['GetSnapshots'](arg1);
}

export function ReadWriteSettings() {
  return window['go']['main']['App']['ReadWriteSettings']();
}
