// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUpdateRepository(arg1:number,arg2:string):Promise<string>;

export function CheckRepoErrors(arg1:number):Promise<string>;

export function ChooseRepository():Promise<string>;

export function CmdCheck():Promise<string>;

export function DeleteRepositoryFromDisk(arg1:number):Promise<string>;

export function DeleteRepositorySetting(arg1:number):Promise<string>;

export function GetRepoInfo(arg1:number):Promise<string>;

export function GetRepoStats(arg1:number):Promise<string>;

export function GetSnapshots(arg1:number):Promise<string>;

export function ReadWriteSettings():Promise<void>;

export function SearchInRepo(arg1:number,arg2:string):Promise<string>;
