// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseRepository() {
  return window['go']['main']['App']['ChooseRepository']();
}

export function GetSnapshots(arg1) {
  return window['go']['main']['App']['GetSnapshots'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
