// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForgetSnapshot(arg1, arg2) {
  return window['go']['main']['App']['ForgetSnapshot'](arg1, arg2);
}

export function GetCurrentRepositoryPath() {
  return window['go']['main']['App']['GetCurrentRepositoryPath']();
}

export function GetRepositoryStats() {
  return window['go']['main']['App']['GetRepositoryStats']();
}

export function InitRepository(arg1, arg2) {
  return window['go']['main']['App']['InitRepository'](arg1, arg2);
}

export function IsRepositoryOpen() {
  return window['go']['main']['App']['IsRepositoryOpen']();
}

export function ListSnapshotFiles(arg1) {
  return window['go']['main']['App']['ListSnapshotFiles'](arg1);
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function OpenRepository(arg1, arg2) {
  return window['go']['main']['App']['OpenRepository'](arg1, arg2);
}

export function PruneRepository() {
  return window['go']['main']['App']['PruneRepository']();
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
