// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restic} from '../models';

export function ForgetSnapshot(arg1:string,arg2:boolean):Promise<void>;

export function GetCurrentRepositoryPath():Promise<string>;

export function GetRepositoryStats():Promise<restic.RepositoryStats>;

export function InitRepository(arg1:string,arg2:string):Promise<void>;

export function IsRepositoryOpen():Promise<boolean>;

export function ListSnapshotFiles(arg1:string):Promise<string>;

export function ListSnapshots():Promise<Array<restic.Snapshot>>;

export function OpenRepository(arg1:string,arg2:string):Promise<void>;

export function PruneRepository():Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;
