// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup(arg1, arg2) {
  return window['go']['main']['App']['Backup'](arg1, arg2);
}

export function CheckRepository() {
  return window['go']['main']['App']['CheckRepository']();
}

export function CloseRepository() {
  return window['go']['main']['App']['CloseRepository']();
}

export function DeleteRepository() {
  return window['go']['main']['App']['DeleteRepository']();
}

export function Find(arg1) {
  return window['go']['main']['App']['Find'](arg1);
}

export function ForgetSnapshot(arg1, arg2) {
  return window['go']['main']['App']['ForgetSnapshot'](arg1, arg2);
}

export function GetCurrentRepositoryPath() {
  return window['go']['main']['App']['GetCurrentRepositoryPath']();
}

export function GetRepositoryStats() {
  return window['go']['main']['App']['GetRepositoryStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InitRepository(arg1, arg2) {
  return window['go']['main']['App']['InitRepository'](arg1, arg2);
}

export function IsMounted() {
  return window['go']['main']['App']['IsMounted']();
}

export function IsRepositoryOpen() {
  return window['go']['main']['App']['IsRepositoryOpen']();
}

export function ListSnapshotFiles(arg1) {
  return window['go']['main']['App']['ListSnapshotFiles'](arg1);
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function MountRepository(arg1) {
  return window['go']['main']['App']['MountRepository'](arg1);
}

export function OpenRepository(arg1, arg2) {
  return window['go']['main']['App']['OpenRepository'](arg1, arg2);
}

export function PruneRepository() {
  return window['go']['main']['App']['PruneRepository']();
}

export function RepairRepository() {
  return window['go']['main']['App']['RepairRepository']();
}

export function RestoreSnapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UnlockRepository() {
  return window['go']['main']['App']['UnlockRepository']();
}

export function UnmountRepository() {
  return window['go']['main']['App']['UnmountRepository']();
}
