// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restic} from '../models';
import {config} from '../models';

export function Backup(arg1:string,arg2:Array<string>):Promise<string>;

export function CheckRepository():Promise<string>;

export function CloseRepository():Promise<void>;

export function DeleteRepository():Promise<void>;

export function Find(arg1:string):Promise<Array<restic.FindResult>>;

export function ForgetSnapshot(arg1:string,arg2:boolean):Promise<void>;

export function GetCurrentRepositoryPath():Promise<string>;

export function GetRepositoryStats():Promise<restic.RepositoryStats>;

export function GetSettings():Promise<config.Config>;

export function InitRepository(arg1:string,arg2:string):Promise<void>;

export function IsMounted():Promise<boolean>;

export function IsRepositoryOpen():Promise<boolean>;

export function ListSnapshotFiles(arg1:string):Promise<Array<restic.LSNode>>;

export function ListSnapshots():Promise<Array<restic.Snapshot>>;

export function MountRepository(arg1:string):Promise<void>;

export function OpenRepository(arg1:string,arg2:string):Promise<void>;

export function PruneRepository():Promise<void>;

export function RepairRepository():Promise<string>;

export function RestoreSnapshot(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<restic.RestoreMessage>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function UnlockRepository():Promise<void>;

export function UnmountRepository():Promise<void>;
